version: '3.0'
services:
  mongo:
    image: mongo
    volumes:
    - ./data:/data/db
  web:
    build: .
    image: geosoft-1:latest
    environment:
      - MONGO_HOST=mongo
    ports:
    - "3000:3000"
    links:
    - mongo
    depends_on:
      - mongo
